added feature incremental sync for product categories
ShoppinPal/StockUp pull request #516
Opened 2022-04-17 10:41 UTC by chronos25

2022-04-17 10:50 UTC, with-shrey requested changes

2022-04-17 10:50 UTC, with-shrey commented on admin/src/app/home/connect/connect.component.html
> +            <!-- <tr>
Remove commented code

2022-04-17 10:50 UTC, with-shrey commented on admin/src/app/home/connect/connect.component.html
> +                <div [ngClass]="{'d-none': !syncing.sales}" class="spinner-border spinner-border-sm spinner-margins"
syncing.sales ?

2022-04-17 10:50 UTC, with-shrey commented on admin/src/app/home/connect/connect.component.ts
> +  /*private syncVendProductTypes() {
remove commented code

2022-04-17 10:50 UTC, with-shrey commented on common/models/org-model.js
> +       /* OrgModel.remoteMethod('syncVendProductTypes', {
commented code

2022-04-17 10:50 UTC, with-shrey commented on common/models/sync-model.js
> +  /*  SyncModel.syncVendProductTypes = function (id, options,versionsAfter = 0) {
commented code

2022-04-17 10:50 UTC, with-shrey commented on workers/syncWorker.js
> -const syncInterval = 300;
revert this

2022-04-17 10:50 UTC, with-shrey commented on workers/workers-v2/fetch-incremental-category/fetch-incremental-category.js
> +    }).catch(function(error){
.catch on new line

2022-04-17 10:50 UTC, with-shrey commented on workers/workers-v2/fetch-incremental-category/fetch-incremental-category.js
> +            }).then(function(response){
new line before .then

2022-04-18 05:30 UTC, chronos25 commented on admin/src/app/home/connect/connect.component.html
> +            <!-- <tr>
resolved !

2022-04-18 05:31 UTC, chronos25 commented on admin/src/app/home/connect/connect.component.html
> +                <div [ngClass]="{'d-none': !syncing.sales}" class="spinner-border spinner-border-sm spinner-margins"
resolved !

2022-04-18 05:32 UTC, chronos25 commented on admin/src/app/home/connect/connect.component.ts
> +  /*private syncVendProductTypes() {
resolved !

2022-04-18 05:39 UTC, chronos25 commented on common/models/sync-model.js
> +  /*  SyncModel.syncVendProductTypes = function (id, options,versionsAfter = 0) {
Resolved !

2022-04-18 05:40 UTC, chronos25 commented on workers/syncWorker.js
> -const syncInterval = 300;
Reverted !

2022-04-18 06:46 UTC, with-shrey commented
LGTM

2022-04-18 06:46 UTC, merged